package com.ilkinbayramov.ninjatalk.localization

import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage(val code: String, val displayName: String) {
    TURKISH("tr", "Türkçe"),
    AZERBAIJANI("az", "Azərbaycanca");

    companion object {
        fun fromCode(code: String?): AppLanguage {
            return entries.find { it.code == code } ?: TURKISH
        }
    }
}

data class AppStrings(
    // Common
    val cancel: String,
    val save: String,
    val back: String,
    val error: String,
    val success: String,
    
    // Auth
    val login: String,
    val register: String,
    val email: String,
    val password: String,
    val forgotPassword: String,
    val forgotPasswordDesc: String,
    val send: String,
    val dontHaveAccount: String,
    val alreadyHaveAccount: String,
    val passwordMismatch: String,
    val passwordsDoNotMatch: String,

    // Settings
    val settingsTitle: String,
    val profile: String,
    val changePassword: String,
    val privacyPolicy: String,
    val blockedUsers: String,
    val language: String,
    val notifications: String,
    val logout: String,
    
    // Privacy
    val privacyPolicyContent: String,

    // Inbox & Chat
    val chats: String,
    val search: String,
    val typeMessage: String,
    val noMessages: String,
    
    // Shuffle
    val shuffle: String,
    val findSomeone: String,
    val filter: String,
    val ageRange: String,
    val gender: String,
    val apply: String,
    val male: String,
    val female: String,
    val any: String,
    val account: String,
    val profileInfo: String,
    val profileInfoDesc: String,
    val application: String,
    val deleteAccount: String,
    val deleteAccountConfirm: String,
    val delete: String,
    val searchSettings: String,
    val editProfile: String,
    val username: String,
    val bio: String,
    val profileLoadError: String,
    val profilePhotoUpdated: String,
    val photoUploadError: String,
    val sessionExpired: String,
    val profileUpdated: String,
    val defaultBio: String,
    val currentPassword: String,
    val newPassword: String,
    val newPasswordConfirm: String,
    val ok: String,
    val noBlockedUsers: String,
    val unblock: String,
    val lastUpdate: String,
    val privacyDataCollectedTitle: String,
    val privacyDataCollectedContent: String,
    val privacyDataUseTitle: String,
    val privacyDataUseContent: String,
    val privacyDataSecurityTitle: String,
    val privacyDataSecurityContent: String,
    val privacyAccountDeletionTitle: String,
    val privacyAccountDeletionContent: String,
    val privacyPermissionsTitle: String,
    val privacyPermissionsContent: String,
    val discoverRealYou: String,
    val usernameOrEmail: String,
    val usernameOrEmailPlaceholder: String,
    val passwordPlaceholder: String,
    val forgotPasswordQuestion: String,
    val dontHaveAccountText: String,
    val signUpText: String,
    val termsOfUse: String,
    val footerText: String,
    val createAccount: String,
    val emailAddress: String,
    val emailPlaceholder: String,
    val choosePassword: String,
    val birthDate: String,
    val datePlaceholder: String,
    val deleteChat: String,
    val deleteChatConfirm: String,
    val blockUser: String,
    val blockUserConfirm: String,
    val block: String,
    val anonymousChat: String,
    val searchUsername: String,
    val noBio: String,
    val reset: String,
    val close: String,
    val age: String,
    val country: String,
    val applyFilters: String,
    val all: String,
    val other: String,
    val chat: String,
    val premium: String,
    val comingSoon: String,
)

val trStrings = AppStrings(
    cancel = "İptal",
    save = "Kaydet",
    back = "Geri",
    error = "Hata",
    success = "Başarılı",

    login = "Giriş Yap",
    register = "Kayıt Ol",
    email = "E-posta",
    password = "Şifre",
    forgotPassword = "Şifremi Unuttum",
    forgotPasswordDesc = "Kayıtlı e-posta adresinizi girin. Size bir şifre sıfırlama linki göndereceğiz.",
    send = "Gönder",
    dontHaveAccount = "Hesabınız yok mu? Kayıt Ol",
    alreadyHaveAccount = "Zaten hesabınız var mı?",
    passwordMismatch = "Şifreler eşleşmiyor",
    passwordsDoNotMatch = "Girdiğiniz şifreler birbiriyle eşleşmiyor.",

    settingsTitle = "Ayarlar",
    profile = "Profil",
    changePassword = "Şifre Değiştir",
    privacyPolicy = "Gizlilik Politikası",
    blockedUsers = "Engellenen Kullanıcılar",
    language = "Dil",
    notifications = "Bildirimler",
    logout = "Çıkış Yap",

    privacyPolicyContent = "Gizlilik ve Güvenlik politikalarımız hakkında detaylı bilgi...",

    chats = "Sohbetler",
    search = "Ara...",
    typeMessage = "Mesaj yazın...",
    noMessages = "Henüz mesaj yok",

    shuffle = "Keşfet",
    findSomeone = "Rastgele Biriyle Eşleş",
    filter = "Filtrele",
    ageRange = "Yaş Aralığı",
    gender = "Cinsiyet",
    apply = "Uygula",
    male = "Erkek",
    female = "Kadın",
    any = "Fark etmez",
    
    account = "Hesap",
    profileInfo = "Profil Bilgileri",
    profileInfoDesc = "Kullanıcı Adı, Biyografi",
    application = "Uygulama",
    deleteAccount = "Hesabı Sil",
    deleteAccountConfirm = "Hesabınızı silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.",
    delete = "Sil",
    searchSettings = "Ayarlarda ara",
    editProfile = "Profil Düzenle",
    username = "Kullanıcı Adı",
    bio = "Biyografi",
    profileLoadError = "Profil yüklenemedi",
    profilePhotoUpdated = "Profil fotoğrafı güncellendi!",
    photoUploadError = "Fotoğraf yüklenemedi",
    sessionExpired = "Oturum süresi dolmuş, lütfen tekrar giriş yapın",
    profileUpdated = "Profil güncellendi!",
    defaultBio = "Yeni insanlarla tanışmayı seviyorum. Bana bir mesaj gönder!",
    currentPassword = "Mevcut Şifre",
    newPassword = "Yeni Şifre",
    newPasswordConfirm = "Yeni Şifre (Tekrar)",
    ok = "Tamam",
    noBlockedUsers = "Engellenmiş kullanıcı yok",
    unblock = "Engeli Kaldır",
    lastUpdate = "Son Güncelleme: 24 Nisan 2026",
    privacyDataCollectedTitle = "1. Toplanan Veriler",
    privacyDataCollectedContent = "NinjaTalk uygulamasını kullanırken e-posta adresiniz, cinsiyetiniz, doğum tarihiniz, biyografiniz ve profil fotoğrafınız uygulamanın temel işlevlerini sağlamak amacıyla toplanmaktadır. Ayrıca, mesajlaşma geçmişiniz ve engellediğiniz kullanıcı bilgileri güvenli bir şekilde sunucularımızda saklanmaktadır.",
    privacyDataUseTitle = "2. Veri Kullanımı",
    privacyDataUseContent = "Toplanan veriler yalnızca hesabınızı yönetmek, diğer kullanıcılarla iletişim kurmanızı sağlamak (mesajlaşma) ve kişiselleştirilmiş bir deneyim sunmak için kullanılır. Verileriniz hiçbir şekilde izniniz olmadan 3. şahıslarla paylaşılmaz.",
    privacyDataSecurityTitle = "3. Veri Güvenliği",
    privacyDataSecurityContent = "Kullanıcı bilgileri, mesajlaşmalar ve oturum açma tokenları, yetkisiz erişime karşı korunmak için güvenli sunucularda barındırılmakta ve şifreli bir şekilde iletilmektedir.",
    privacyAccountDeletionTitle = "4. Hesap Silme ve Veri İptali",
    privacyAccountDeletionContent = "İstediğiniz zaman Ayarlar bölümünden 'Hesabı Sil' seçeneğini kullanarak hesabınızı ve ilişkili tüm verilerinizi (mesajlar, profil bilgileri, ayarlar) kalıcı olarak silebilirsiniz. Hesap silindikten sonra verilerin geri getirilmesi mümkün değildir.",
    privacyPermissionsTitle = "5. Uygulama İzinleri",
    privacyPermissionsContent = "Uygulama, size yeni mesajları anında bildirebilmek için bildirim izni isteyebilir. Bu izinleri cihaz ayarlarınızdan veya uygulama içi Ayarlar bölümünden dilediğiniz zaman yönetebilirsiniz.",
    discoverRealYou = "Gerçek Seni Keşfet",
    usernameOrEmail = "Kullanıcı Adı veya E-posta",
    usernameOrEmailPlaceholder = "E-postanızı girin",
    passwordPlaceholder = "Şifrenizi girin",
    forgotPasswordQuestion = "Şifremi Unuttum?",
    dontHaveAccountText = "Hesabın yok mu? ",
    signUpText = "Kaydol",
    termsOfUse = "Kullanım Koşulları",
    footerText = "Gizlilik Politikası  ·  Kullanım Koşulları",
    createAccount = "Hesabını Oluştur",
    emailAddress = "E-posta Adresi",
    emailPlaceholder = "E-posta adresini gir",
    choosePassword = "Bir şifre belirle",
    birthDate = "Doğum Tarihi",
    datePlaceholder = "GG/AA/YYYY",
    deleteChat = "Sohbeti Sil",
    deleteChatConfirm = "Bu sohbeti silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.",
    blockUser = "Kullanıcıyı Engelle",
    blockUserConfirm = "Bu kullanıcıyı engellemek istediğinizden emin misiniz? Engelledikten sonra bu kullanıcıdan mesaj alamayacaksınız.",
    block = "Engelle",
    anonymousChat = "Anonim Sohbet",
    searchUsername = "Kullanıcı adı ara...",
    noBio = "Henüz bir biyografi yok.",
    reset = "Sıfırla",
    close = "Kapat",
    age = "YAŞ",
    country = "ÜLKE",
    applyFilters = "Filtreleri Uygula",
    all = "Tümü",
    other = "Diğer",
    chat = "Sohbet",
    premium = "Premium",
    comingSoon = "Yakında",
)

val azStrings = AppStrings(
    cancel = "Ləğv et",
    save = "Yadda saxla",
    back = "Geri",
    error = "Xəta",
    success = "Uğurlu",

    login = "Daxil ol",
    register = "Qeydiyyatdan keç",
    email = "E-poçt",
    password = "Şifrə",
    forgotPassword = "Şifrəmi Unutdum",
    forgotPasswordDesc = "Qeydiyyatdan keçdiyiniz e-poçt ünvanını daxil edin. Sizə şifrə sıfırlama linki göndərəcəyik.",
    send = "Göndər",
    dontHaveAccount = "Hesabınız yoxdur? Qeydiyyatdan keç",
    alreadyHaveAccount = "Artıq hesabınız var?",
    passwordMismatch = "Şifrələr uyğun gəlmir",
    passwordsDoNotMatch = "Daxil etdiyiniz şifrələr bir-biri ilə uyğun gəlmir.",

    settingsTitle = "Tənzimləmələr",
    profile = "Profil",
    changePassword = "Şifrəni Dəyiş",
    privacyPolicy = "Məxfilik Siyasəti",
    blockedUsers = "Bloklanmış İstifadəçilər",
    language = "Dil",
    notifications = "Bildirişlər",
    logout = "Çıxış et",

    privacyPolicyContent = "Məxfilik və Təhlükəsizlik siyasətlərimiz haqqında ətraflı məlumat...",

    chats = "Söhbətlər",
    search = "Axtar...",
    typeMessage = "Mesaj yazın...",
    noMessages = "Hələ mesaj yoxdur",

    shuffle = "Kəşf et",
    findSomeone = "Təsadüfi Biri ilə Eşləş",
    filter = "Filtrlə",
    ageRange = "Yaş Aralığı",
    gender = "Cins",
    apply = "Tətbiq et",
    male = "Kişi",
    female = "Qadın",
    any = "Fərq etməz",
    
    account = "Hesab",
    profileInfo = "Profil Məlumatları",
    profileInfoDesc = "İstifadəçi Adı, Bioqrafiya",
    application = "Tətbiq",
    deleteAccount = "Hesabı Sil",
    deleteAccountConfirm = "Hesabınızı silmək istədiyinizdən əminsinizmi? Bu əməliyyat geri qaytarıla bilməz.",
    delete = "Sil",
    searchSettings = "Tənzimləmələrdə axtar",
    editProfile = "Profili Redaktə et",
    username = "İstifadəçi Adı",
    bio = "Bioqrafiya",
    profileLoadError = "Profil yüklənə bilmədi",
    profilePhotoUpdated = "Profil şəkli yeniləndi!",
    photoUploadError = "Şəkil yüklənə bilmədi",
    sessionExpired = "Sessiya müddəti bitib, zəhmət olmasa yenidən daxil olun",
    profileUpdated = "Profil yeniləndi!",
    defaultBio = "Yeni insanlarla tanış olmağı sevirəm. Mənə bir mesaj göndər!",
    currentPassword = "Cari Şifrə",
    newPassword = "Yeni Şifrə",
    newPasswordConfirm = "Yeni Şifrə (Təkrar)",
    ok = "Tamam",
    noBlockedUsers = "Bloklanmış istifadəçi yoxdur",
    unblock = "Bloku Aç",
    lastUpdate = "Son Yenilənmə: 24 Aprel 2026",
    privacyDataCollectedTitle = "1. Toplanan Məlumatlar",
    privacyDataCollectedContent = "NinjaTalk tətbiqindən istifadə edərkən e-poçt ünvanınız, cinsiniz, doğum tarixiniz, bioqrafiyanız və profil şəkliniz tətbiqin əsas funksiyalarını təmin etmək məqsədilə toplanır. Həmçinin, mesajlaşma keçmişiniz və blokladığınız istifadəçi məlumatları serverlərimizdə təhlükəsiz şəkildə saxlanılır.",
    privacyDataUseTitle = "2. Məlumatların İstifadəsi",
    privacyDataUseContent = "Toplanan məlumatlar yalnız hesabınızı idarə etmək, digər istifadəçilərlə əlaqə qurmağınızı (mesajlaşma) təmin etmək və fərdiləşdirilmiş təcrübə təqdim etmək üçün istifadə olunur. Məlumatlarınız heç bir halda icazəniz olmadan 3-cü tərəflərlə paylaşılmır.",
    privacyDataSecurityTitle = "3. Məlumat Təhlükəsizliyi",
    privacyDataSecurityContent = "İstifadəçi məlumatları, mesajlaşmalar və daxil olma tokenləri icazəsiz girişdən qorunmaq üçün təhlükəsiz serverlərdə saxlanılır və şifrələnmiş şəkildə ötürülür.",
    privacyAccountDeletionTitle = "4. Hesabın Silinməsi və Məlumatların Ləğvi",
    privacyAccountDeletionContent = "İstədiyiniz zaman Tənzimləmələr bölməsindən 'Hesabı Sil' seçimini edərək hesabınızı və əlaqəli bütün məlumatlarınızı (mesajlar, profil məlumatları, tənzimləmələr) həmişəlik silə bilərsiniz. Hesab silindikdən sonra məlumatların geri qaytarılması mümkün deyil.",
    privacyPermissionsTitle = "5. Tətbiq İcazələri",
    privacyPermissionsContent = "Tətbiq sizə yeni mesajları dərhal bildirə bilmək üçün bildiriş icazəsi istəyə bilər. Bu icazələri cihazınızın tənzimləmələrindən və ya tətbiq daxili Tənzimləmələr bölməsindən istədiyiniz zaman idarə edə bilərsiniz.",
    discoverRealYou = "Əsl Özünü Kəşf Et",
    usernameOrEmail = "İstifadəçi Adı və ya E-poçt",
    usernameOrEmailPlaceholder = "E-poçtunuzu daxil edin",
    passwordPlaceholder = "Şifrənizi daxil edin",
    forgotPasswordQuestion = "Şifrəmi Unutdum?",
    dontHaveAccountText = "Hesabın yoxdur? ",
    signUpText = "Qeydiyyat",
    termsOfUse = "İstifadə Şərtləri",
    footerText = "Məxfilik Siyasəti  ·  İstifadə Şərtləri",
    createAccount = "Hesabını Yarat",
    emailAddress = "E-poçt Ünvanı",
    emailPlaceholder = "E-poçt ünvanını daxil et",
    choosePassword = "Bir şifrə təyin et",
    birthDate = "Doğum Tarixi",
    datePlaceholder = "GG/AA/İİİİ",
    deleteChat = "Söhbəti Sil",
    deleteChatConfirm = "Bu söhbəti silmək istədiyinizdən əminsinizmi? Bu əməliyyat geri qaytarıla bilməz.",
    blockUser = "İstifadəçini Blokla",
    blockUserConfirm = "Bu istifadəçini bloklamaq istədiyinizdən əminsinizmi? Blokladıqdan sonra bu istifadəçidən mesaj ala bilməyəcəksiniz.",
    block = "Blokla",
    anonymousChat = "Anonim Söhbət",
    searchUsername = "İstifadəçi adı axtar...",
    noBio = "Hələ bir bioqrafiya yoxdur.",
    reset = "Sıfırla",
    close = "Bağla",
    age = "YAŞ",
    country = "ÖLKƏ",
    applyFilters = "Filtrləri Tətbiq Et",
    all = "Hamısı",
    other = "Digər",
    chat = "Söhbət",
    premium = "Premium",
    comingSoon = "Tezliklə",
)

val LocalAppStrings = staticCompositionLocalOf { trStrings }
